In [33]:
import numpy as np

x = np.array([[1 , 3 , 5 ,7] , [1, 5 , 9 , 10], [7,10 ,1 ,3]])
y = np.array([1 , -1 , 1])
w = np.array([[1,2,3,4]])

pred = np.sign(y.reshape(3,1) * np.inner(x,w)).reshape(3,)
wrong = pred == -1
print(pred)
print(wrong)
print(np.where(wrong)[0][0])

[ 1 -1  1]
[False  True False]
1


In [36]:
def func():
    
    return 1, 2

print(func()[1])

2


In [41]:
x = np.array([[1,3,4] , [7,6,10], [5, 4,3]])
m = np.random.permutation(3)
print(m)
x = x[m]
print(x)

[0 2 1]
[[ 1  3  4]
 [ 5  4  3]
 [ 7  6 10]]


In [43]:
x = np.array([[1 , 2]])
print(x.shape[])

(1, 2)


In [45]:
x = np.array([np.zeros(4)])
print(x)

[[0. 0. 0. 0.]]


In [46]:
print(np.sign([0 , 0 ,1]))

[0 0 1]
